---
all:
  platform: cisco_ios

router:
  platform: cisco_ios
router1:
  platform: cisco_ios
router2:
  platform: cisco_ios

switch:
  platform: cisco_ios
coreswitch1:
  platform: cisco_ios
coreswitch2:
  platform: cisco_ios

pc:
  platform: cisco_ios
pc1:
  platform: cisco_ios
pc2:
  platform: cisco_ios